// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebMyAnimeList.Data;

#nullable disable

namespace WebMyAnimeList.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251115135657_юзерсоздан")]
    partial class юзерсоздан
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimationStudioAnime", b =>
                {
                    b.Property<int>("AnimesAnimeId")
                        .HasColumnType("integer");

                    b.Property<int>("StudioId")
                        .HasColumnType("integer");

                    b.HasKey("AnimesAnimeId", "StudioId");

                    b.HasIndex("StudioId");

                    b.ToTable("AnimationStudioAnime");
                });

            modelBuilder.Entity("AnimeSeriesUser", b =>
                {
                    b.Property<int>("AnimeSeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("integer");

                    b.HasKey("AnimeSeriesId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("AnimeSeriesUser");
                });

            modelBuilder.Entity("WebMyAnimeList.Data.Entities.AnimationStudio", b =>
                {
                    b.Property<int>("StudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudioId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("YearOfFoundation")
                        .HasColumnType("integer");

                    b.HasKey("StudioId");

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("WebMyAnimeList.Data.Entities.Anime", b =>
                {
                    b.Property<int>("AnimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnimeId"));

                    b.Property<int>("CuontSerios")
                        .HasColumnType("integer");

                    b.Property<int>("CuontSezon")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("GenreAnime")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(210)
                        .HasColumnType("character varying(210)");

                    b.HasKey("AnimeId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("WebMyAnimeList.Data.Entities.AnimeSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<int>("StudioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("StudioId");

                    b.ToTable("AnimeSeries");
                });

            modelBuilder.Entity("WebMyAnimeList.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnimationStudioAnime", b =>
                {
                    b.HasOne("WebMyAnimeList.Data.Entities.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimesAnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMyAnimeList.Data.Entities.AnimationStudio", null)
                        .WithMany()
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeSeriesUser", b =>
                {
                    b.HasOne("WebMyAnimeList.Data.Entities.AnimeSeries", null)
                        .WithMany()
                        .HasForeignKey("AnimeSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMyAnimeList.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebMyAnimeList.Data.Entities.AnimeSeries", b =>
                {
                    b.HasOne("WebMyAnimeList.Data.Entities.Anime", "Anime")
                        .WithMany("AnimeSeries")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMyAnimeList.Data.Entities.AnimationStudio", "Studio")
                        .WithMany("AnimeSeries")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("WebMyAnimeList.Data.Entities.AnimationStudio", b =>
                {
                    b.Navigation("AnimeSeries");
                });

            modelBuilder.Entity("WebMyAnimeList.Data.Entities.Anime", b =>
                {
                    b.Navigation("AnimeSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
